[package]
name = "ieee-paper"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Hugo Coto Flórez <hugoocoto>"]
license = "MIT"
description = "A multilanguage Typst template for writing academic papers in the IEEE style."
repository = "https://github.com/hugoocoto/ieee-paper"
keywords = ["ieee", "article", "paper", "science"]
categories = ["report", "paper"]
disciplines = ["computer-science", "engineering"]
exclude = ["README.md", "image.png"]

[template]
path = "template"
entrypoint = "blank.typ"
